### ISSUE TITLE
Initial create throws exception

### ISSUE THREAD

**Issue by await** [paltman-archive/nashvegas#18]
Ran a simple test to create some tables, all the tables got created, but got the following error:

Any insight as to why the connection is getting 'lost'?

domU-12-31-39-0E-26-41:/var/www/publisher/infographs> python ./manage.py upgradedb --execute --path etc/db/migrations/
Executing 0001_initial.sql... success
Emitting post sync signal.
Exception _mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query') in <bound method Cursor.__del__ of <MySQLdb.cursors.Cursor object at 0x1f3c990>> ignored
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_manager(settings)
  File "/home/build/.virtualenv/publisher/lib/python2.6/site-packages/django/core/management/**init**.py", line 438, in execute_manager
    utility.execute()
  File "/home/build/.virtualenv/publisher/lib/python2.6/site-packages/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/build/.virtualenv/publisher/lib/python2.6/site-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/home/build/.virtualenv/publisher/lib/python2.6/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(_args, *_options)
  File "/home/build/.virtualenv/publisher/lib/python2.6/site-packages/nashvegas/management/commands/upgradedb.py", line 297, in handle
    self.execute_migrations(show_traceback=True)
  File "/home/build/.virtualenv/publisher/lib/python2.6/site-packages/django/db/transaction.py", line 340, in _commit_manually
    leave_transaction_management(using=db)
  File "/home/build/.virtualenv/publisher/lib/python2.6/site-packages/django/db/transaction.py", line 87, in leave_transaction_management
    raise TransactionManagementError("Transaction managed block ended with pending COMMIT/ROLLBACK")
django.db.transaction.TransactionManagementError: Transaction managed block ended with pending COMMIT/ROLLBACK

**Comment by paltman** [comment]
I suspect your migration(s) have BEGIN/COMMIT in the file.  These should be removed as the transaction scope is now handled within nashvegas.

**Comment by peterbe** [comment]
I'm getting the same error. No BEGIN/COMMIT anywhere in the .sql files. I suspect something else is hiding something and it getting tangled in its own error handling. Investigating some more.
